[versions]
agp = "8.13.1"
glide = "4.16.0"
koinAndroid = "3.3.0"
mockitoCore = "5.18.0"
retrofit = "2.9.0"

convertergson= "2.9.0"
gson = "2.10"
kotlin = "1.9.24"
coreKtx = "1.10.1"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.9.3"
constraintlayout = "2.2.0"
contentpager = "1.0.0"
fragment = "1.8.0-alpha02"
navigationFragment= "2.5.3"
navigationUi = "2.5.3"

[libraries]


koin-android = { module = "io.insert-koin:koin-android", version.ref = "koinAndroid" }
livedata = {module = "androidx.lifecycle:lifecycle-livedata-ktx",version = "2.5.1"}
viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version = "2.5.1" }
activity = { module = "androidx.activity:activity-ktx", version = "1.6.1" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
glide = { module = "com.github.bumptech.glide:glide", name = "glide", version.ref = "glide" }
gson = {module = "com.google.code.gson:gson", name = "gson", version.ref = "gson" }
retrofit = {module = "com.squareup.retrofit2:retrofit", name = "retrofit", version.ref = "retrofit" }

convertergson = {module = "com.squareup.retrofit2:converter-gson", name = "convertergson", version.ref = "convertergson" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-contentpager = { group = "androidx.contentpager", name = "contentpager", version.ref = "contentpager" }
androidx-fragment-compose = { group = "androidx.fragment", name = "fragment-compose", version.ref = "fragment" }
navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigationFragment" }
navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigationUi" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

